# Healthcare Data Analytics Project
## Step 2: Data Cleaning

In [2]:
import pandas as pd
import numpy as np

In [5]:
# loading our raw data-
data=pd.read_csv(r"../data/raw/healthcare_data.csv")

In [6]:
data.head()

,Patient_ID,Age,Gender,City,Disease,Doctor_Assigned,Hospital_Department,Treatment_Cost,Insurance_Cover,Payment_Status,Outcome,Admission_Date,Length_of_Stay,Discharge_Date,Final_Bill
0,1137,9,Female,Mumbai,COVID-19,Dr. Mehta,Cardiology,23037,5088.0,Pending,Recovered,2023-02-23,4,2023-02-27,17949
1,1473,35,Male,Bangalore,Cancer,Dr. Khan,ICU,24584,NaN,Pending,Deceased,2023-02-28,8,2023-03-08,21573
2,1188,32,Female,Delhi,Flu,Dr. Khan,Oncology,14596,6374.0,Paid,Recovered,2023-09-21,8,2023-09-29,8222
3,1447,76,Female,Delhi,Flu,Dr. Khan,Oncology,15403,16434.0,Pending,Critical,2023-04-06,14,2023-04-20,-1031
4,1247,50,Male,Delhi,Diabetes,Dr. Sharma,General,14518,12093.0,Paid,Deceased,2023-08-30,8,2023-09-07,2425

In [7]:
# for checking the shape of the data-
data.shape

(500, 15)

In [13]:
# for checking the info of the data-
data.info()

# INFO SHOWS - We have 2 columns i.e Insurance cover and Doctor_Assigend where exists 25 missing values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Patient_ID           500 non-null    int64
 1   Age                  500 non-null    int64
 2   Gender               500 non-null    object
 3   City                 500 non-null    object
 4   Disease              500 non-null    object
 5   Doctor_Assigned      475 non-null    object
 6   Hospital_Department  500 non-null    object
 7   Treatment_Cost       500 non-null    int64
 8   Insurance_Cover      475 non-null    float64
 9   Payment_Status       500 non-null    object
 10  Outcome              500 non-null    object
 11  Admission_Date       500 non-null    object
 12  Length_of_Stay       500 non-null    int64
 13  Discharge_Date       500 non-null    object
 14  Final_Bill           500 non-null    int64
dtypes: float64(1), int64(5), object(9)
memory usage: 58.7+ KB

In [16]:
# for the statistical analysis of the data-
data.describe()

# SHOWS - It will show us the basic stats of the integer datatype columns like thier count, mean, std., 25% etc...

,Patient_ID,Age,Treatment_Cost,Insurance_Cover,Length_of_Stay,Final_Bill
count,500.000000,500.000000,500.000000,475.000000,500.000000,500.000000
mean,1249.500000,43.000000,26945.794000,15146.734737,7.710000,11721.042000
std,144.481833,25.572092,12709.059301,8149.917723,4.010745,15117.890157
min,1000.000000,1.000000,5097.000000,1040.000000,1.000000,-22568.000000
25%,1124.750000,21.000000,16088.250000,8193.000000,4.000000,150.750000
50%,1249.500000,43.500000,27215.500000,14749.000000,8.000000,13164.000000
75%,1374.250000,63.000000,37159.250000,21831.500000,11.000000,22600.250000
max,1499.000000,89.000000,49918.000000,29941.000000,14.000000,44831.000000

In [22]:
# now we have to check the missing values-
data.isna().sum(axis=0)

Patient_ID              0
Age                     0
Gender                  0
City                    0
Disease                 0
Doctor_Assigned        25
Hospital_Department     0
Treatment_Cost          0
Insurance_Cover        25
Payment_Status          0
Outcome                 0
Admission_Date          0
Length_of_Stay          0
Discharge_Date          0
Final_Bill              0
dtype: int64

In [26]:
#  now let us fill the missing values on the column named - Doctor_Assigned -
data.fillna({"Doctor_Assigned":"Unknown"},inplace=True)

In [27]:
# to fill the missing values in the Insurance_Cover-
data.fillna({"Insurance_Cover":data["Insurance_Cover"].median()},inplace=True)

In [28]:
#  verify the missing values again -
data.isna().sum()

Patient_ID             0
Age                    0
Gender                 0
City                   0
Disease                0
Doctor_Assigned        0
Hospital_Department    0
Treatment_Cost         0
Insurance_Cover        0
Payment_Status         0
Outcome                0
Admission_Date         0
Length_of_Stay         0
Discharge_Date         0
Final_Bill             0
dtype: int64

In [30]:
# for checing the duplicates -
data.duplicated().sum()

0

In [33]:
# if exists - to remove the dupliactes -
data.drop_duplicates(keep=False,inplace=True)

In [36]:
# Lets calculate the cost per day- total cost / days of stay-
data["Cost_per_Day"] = data["Final_Bill"] / data["Length_of_Stay"]
data

,Patient_ID,Age,Gender,City,Disease,Doctor_Assigned,Hospital_Department,Treatment_Cost,Insurance_Cover,Payment_Status,Outcome,Admission_Date,Length_of_Stay,Discharge_Date,Final_Bill,Cost_per_Day
0,1137,9,Female,Mumbai,COVID-19,Dr. Mehta,Cardiology,23037,5088.0,Pending,Recovered,2023-02-23,4,2023-02-27,17949,4487.250000
1,1473,35,Male,Bangalore,Cancer,Dr. Khan,ICU,24584,14749.0,Pending,Deceased,2023-02-28,8,2023-03-08,21573,2696.625000
2,1188,32,Female,Delhi,Flu,Dr. Khan,Oncology,14596,6374.0,Paid,Recovered,2023-09-21,8,2023-09-29,8222,1027.750000
3,1447,76,Female,Delhi,Flu,Dr. Khan,Oncology,15403,16434.0,Pending,Critical,2023-04-06,14,2023-04-20,-1031,-73.642857
4,1247,50,Male,Delhi,Diabetes,Dr. Sharma,General,14518,12093.0,Paid,Deceased,2023-08-30,8,2023-09-07,2425,303.125000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,1067,6,Female,Jaipur,Heart Disease,Dr. Sharma,ICU,11979,26646.0,Paid,Recovered,2023-04-08,8,2023-04-16,-14667,-1833.375000
496,1010,24,Male,Delhi,Flu,Dr. Singh,ICU,47080,12739.0,Paid,Critical,2023-04-23,7,2023-04-30,34341,4905.857143
497,1377,66,Female,Jaipur,COVID-19,Dr. Khan,General,23474,21584.0,Pending,Critical,2023-07-26,2,2023-07-28,1890,945.000000
498,1094,29,Male,Delhi,Cancer,Dr. Mehta,General,17275,23499.0,Paid,Deceased,2023-09-23,13,2023-10-06,-6224,-478.769231
499,1442,78,Female,Mumbai,Cancer,Dr. Sharma,Cardiology,34450,7990.0,Paid,Recovered,2023-05-12,12,2023-05-24,26460,2205.000000

In [39]:
# create age groups-
data["Age_Group"] = pd.cut(
    data["Age"],
    bins=[0, 18, 40, 60, 100],
    labels=["Child", "Young", "Adult", "Senior"]
)
data

,Patient_ID,Age,Gender,City,Disease,Doctor_Assigned,Hospital_Department,Treatment_Cost,Insurance_Cover,Payment_Status,Outcome,Admission_Date,Length_of_Stay,Discharge_Date,Final_Bill,Cost_per_Day,Age_Group
0,1137,9,Female,Mumbai,COVID-19,Dr. Mehta,Cardiology,23037,5088.0,Pending,Recovered,2023-02-23,4,2023-02-27,17949,4487.250000,Child
1,1473,35,Male,Bangalore,Cancer,Dr. Khan,ICU,24584,14749.0,Pending,Deceased,2023-02-28,8,2023-03-08,21573,2696.625000,Young
2,1188,32,Female,Delhi,Flu,Dr. Khan,Oncology,14596,6374.0,Paid,Recovered,2023-09-21,8,2023-09-29,8222,1027.750000,Young
3,1447,76,Female,Delhi,Flu,Dr. Khan,Oncology,15403,16434.0,Pending,Critical,2023-04-06,14,2023-04-20,-1031,-73.642857,Senior
4,1247,50,Male,Delhi,Diabetes,Dr. Sharma,General,14518,12093.0,Paid,Deceased,2023-08-30,8,2023-09-07,2425,303.125000,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,1067,6,Female,Jaipur,Heart Disease,Dr. Sharma,ICU,11979,26646.0,Paid,Recovered,2023-04-08,8,2023-04-16,-14667,-1833.375000,Child
496,1010,24,Male,Delhi,Flu,Dr. Singh,ICU,47080,12739.0,Paid,Critical,2023-04-23,7,2023-04-30,34341,4905.857143,Young
497,1377,66,Female,Jaipur,COVID-19,Dr. Khan,General,23474,21584.0,Pending,Critical,2023-07-26,2,2023-07-28,1890,945.000000,Senior
498,1094,29,Male,Delhi,Cancer,Dr. Mehta,General,17275,23499.0,Paid,Deceased,2023-09-23,13,2023-10-06,-6224,-478.769231,Young
499,1442,78,Female,Mumbai,Cancer,Dr. Sharma,Cardiology,34450,7990.0,Paid,Recovered,2023-05-12,12,2023-05-24,26460,2205.000000,Senior

In [41]:
# covert the columns that are having dates into date format datatype-
data["Admission_Date"] = pd.to_datetime(data["Admission_Date"])
data["Discharge_Date"] = pd.to_datetime(data["Discharge_Date"])
data

,Patient_ID,Age,Gender,City,Disease,Doctor_Assigned,Hospital_Department,Treatment_Cost,Insurance_Cover,Payment_Status,Outcome,Admission_Date,Length_of_Stay,Discharge_Date,Final_Bill,Cost_per_Day,Age_Group
0,1137,9,Female,Mumbai,COVID-19,Dr. Mehta,Cardiology,23037,5088.0,Pending,Recovered,2023-02-23,4,2023-02-27,17949,4487.250000,Child
1,1473,35,Male,Bangalore,Cancer,Dr. Khan,ICU,24584,14749.0,Pending,Deceased,2023-02-28,8,2023-03-08,21573,2696.625000,Young
2,1188,32,Female,Delhi,Flu,Dr. Khan,Oncology,14596,6374.0,Paid,Recovered,2023-09-21,8,2023-09-29,8222,1027.750000,Young
3,1447,76,Female,Delhi,Flu,Dr. Khan,Oncology,15403,16434.0,Pending,Critical,2023-04-06,14,2023-04-20,-1031,-73.642857,Senior
4,1247,50,Male,Delhi,Diabetes,Dr. Sharma,General,14518,12093.0,Paid,Deceased,2023-08-30,8,2023-09-07,2425,303.125000,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,1067,6,Female,Jaipur,Heart Disease,Dr. Sharma,ICU,11979,26646.0,Paid,Recovered,2023-04-08,8,2023-04-16,-14667,-1833.375000,Child
496,1010,24,Male,Delhi,Flu,Dr. Singh,ICU,47080,12739.0,Paid,Critical,2023-04-23,7,2023-04-30,34341,4905.857143,Young
497,1377,66,Female,Jaipur,COVID-19,Dr. Khan,General,23474,21584.0,Pending,Critical,2023-07-26,2,2023-07-28,1890,945.000000,Senior
498,1094,29,Male,Delhi,Cancer,Dr. Mehta,General,17275,23499.0,Paid,Deceased,2023-09-23,13,2023-10-06,-6224,-478.769231,Young
499,1442,78,Female,Mumbai,Cancer,Dr. Sharma,Cardiology,34450,7990.0,Paid,Recovered,2023-05-12,12,2023-05-24,26460,2205.000000,Senior

In [42]:
# Final check our cleaned dataset-
data.head()

,Patient_ID,Age,Gender,City,Disease,Doctor_Assigned,Hospital_Department,Treatment_Cost,Insurance_Cover,Payment_Status,Outcome,Admission_Date,Length_of_Stay,Discharge_Date,Final_Bill,Cost_per_Day,Age_Group
0,1137,9,Female,Mumbai,COVID-19,Dr. Mehta,Cardiology,23037,5088.0,Pending,Recovered,2023-02-23,4,2023-02-27,17949,4487.250000,Child
1,1473,35,Male,Bangalore,Cancer,Dr. Khan,ICU,24584,14749.0,Pending,Deceased,2023-02-28,8,2023-03-08,21573,2696.625000,Young
2,1188,32,Female,Delhi,Flu,Dr. Khan,Oncology,14596,6374.0,Paid,Recovered,2023-09-21,8,2023-09-29,8222,1027.750000,Young
3,1447,76,Female,Delhi,Flu,Dr. Khan,Oncology,15403,16434.0,Pending,Critical,2023-04-06,14,2023-04-20,-1031,-73.642857,Senior
4,1247,50,Male,Delhi,Diabetes,Dr. Sharma,General,14518,12093.0,Paid,Deceased,2023-08-30,8,2023-09-07,2425,303.125000,Adult

In [43]:
# lets save this clean data in our "Processed" file of data-
data.to_csv("../data/processed/cleaned_healthcare_data.csv", index=False)